#### 1) Matrix manipulation - Swap the second and fourth rows of the data matrix.

In [1]:
import numpy as np

In [2]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
data

array([[ 9, 72, 99, 85, 75],
       [88, 19, 41, 46, 61],
       [66, 45, 45, 47, 38],
       [41, 18, 99,  9, 96],
       [46, 26, 12,  1,  6]])

In [3]:
data[1], data[3] = data[3].copy(), data[1].copy()
data

array([[ 9, 72, 99, 85, 75],
       [41, 18, 99,  9, 96],
       [66, 45, 45, 47, 38],
       [88, 19, 41, 46, 61],
       [46, 26, 12,  1,  6]])

#### 2) Normalization- Normalize all the elements in the data matrix. In this context, normalizing means to scale the values in such a way that they fall within the range of 0 and 1. To achieve this, subtract the minimum value from each element and divide by the range (max-min).

In [4]:
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
normalized_data

array([[0.08163265, 0.7244898 , 1.        , 0.85714286, 0.75510204],
       [0.40816327, 0.17346939, 1.        , 0.08163265, 0.96938776],
       [0.66326531, 0.44897959, 0.44897959, 0.46938776, 0.37755102],
       [0.8877551 , 0.18367347, 0.40816327, 0.45918367, 0.6122449 ],
       [0.45918367, 0.25510204, 0.1122449 , 0.        , 0.05102041]])

#### 3) Z-score normalization - Standardize the elements in the data matrix using Z-score normalization. In this method, all the elements will be rescaled to have a mean of 0 and a standard deviation of 1. The formula for Z-score normalization is (X - mean) / std , where ( X ) is the element in the data matrix.



In [5]:
z_score_data = (data - np.mean(data)) / np.std(data)
z_score_data

array([[-1.27177517,  0.80392005,  1.69350372,  1.23223811,  0.90276268],
       [-0.21745378, -0.97524728,  1.69350372, -1.27177517,  1.59466109],
       [ 0.60623479, -0.08566361, -0.08566361, -0.01976853, -0.31629641],
       [ 1.33108074, -0.94229973, -0.21745378, -0.05271607,  0.44149708],
       [-0.05271607, -0.71166693, -1.17293254, -1.53535551, -1.37061779]])

#### 4) Array splitting - Reshape the data matrix into a vector (Hint: use np.ravel) and split this array into five equal-sized sub-arrays.

In [6]:
# Reshape the data matrix into a vector
vector_data = np.ravel(data)

# Split the vector into five equal-sized sub-arrays
split_data = np.array_split(vector_data, 5)

# Print the sub-arrays
for i, sub_array in enumerate(split_data):
    print(f"Sub-array {i + 1}:")
    print(sub_array)

Sub-array 1:
[ 9 72 99 85 75]
Sub-array 2:
[41 18 99  9 96]
Sub-array 3:
[66 45 45 47 38]
Sub-array 4:
[88 19 41 46 61]
Sub-array 5:
[46 26 12  1  6]


#### 5) Dot product - Create two vectors of size 5 with any values. Compute the dot product of the two vectors*.

In [7]:
vector1 = np.array([3, 5, 6, 7, 8])
vector2 = np.array([2, 4, 6, 8, 10])

dot_product = np.dot(vector1, vector2)

dot_product

198

#### 6) Matrix multiplication - Create another 3x3 matrix with any values (let’s call it data2). Perform matrix multiplication (dot product of data (first 3x3 part) and data2).

In [8]:
data2 = np.array([[10, 22, 30], [40, 50, 61], [70, 80, 90]])  # Example 3x3 matrix
data2_matrix = data[:3, :3]

# Perform matrix multiplication (dot product) between 'data2_matrix' and 'data2'
result = np.dot(data2_matrix, data2)

# Print the result
print("Matrix Multiplication Result:")
print(result)

Matrix Multiplication Result:
[[ 9900 11718 13572]
 [ 8060  9722 11238]
 [ 5610  7302  8775]]


#### 7) Inverse of a matrix - Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.

In [9]:
# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

# Multiply the identity matrix by 2
scaled_identity = 2 * identity_matrix

# Compute the inverse of the scaled identity matrix
inverse_matrix = np.linalg.inv(scaled_identity)

# Print the results
print("Original Identity Matrix:")
print(identity_matrix)

print("\nScaled Identity Matrix (multiplied by 2):")
print(scaled_identity)

print("\nInverse of Scaled Identity Matrix:")
print(inverse_matrix)

Original Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Scaled Identity Matrix (multiplied by 2):
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

Inverse of Scaled Identity Matrix:
[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


#### 8) Eigenvalues and eigenvectors - For the first 3x3 part of the data matrix, compute the eigenvalues and eigenvectors*.

In [10]:
data_matrix = data[:3, :3]

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(data_matrix)

# Print the results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[162.9999771  +0.j         -45.49998855+14.09770285j
 -45.49998855-14.09770285j]

Eigenvectors:
[[ 0.6176671 +0.j          0.14004734-0.5171203j   0.14004734+0.5171203j ]
 [ 0.55504647+0.j          0.63524277+0.j          0.63524277-0.j        ]
 [ 0.55714519+0.j         -0.46545303+0.30462016j -0.46545303-0.30462016j]]


#### 9) Find missing values - Replace random 5 elements in the data matrix with np.nan. Find the indices of the missing values.

In [11]:
# Create the data matrix
data = np.array(np.random.randint(1, 100, size=25), dtype=float).reshape(5, 5)

# Replace 5 random elements with np.nan
num_elements_to_replace = 5
indices_to_replace = np.random.choice(data.size, size=num_elements_to_replace, replace=False)
data.ravel()[indices_to_replace] = np.nan

# Find the indices of missing values (np.nan)
missing_value_indices = np.argwhere(np.isnan(data))

# Print the data matrix with missing values and their indices
print("Data Matrix with Missing Values:")
print(data)

print("\nIndices of Missing Values:")
print(missing_value_indices)

Data Matrix with Missing Values:
[[67. 14. 20. 52. nan]
 [55. 51. 50. nan 99.]
 [31. 91. 86. nan 30.]
 [85. 80. 19. 34. nan]
 [22. nan 59. 92. 46.]]

Indices of Missing Values:
[[0 4]
 [1 3]
 [2 3]
 [3 4]
 [4 1]]


In [12]:
# Replace 5 random elements with np.nan
num_elements_to_replace = 5
indices_to_replace = np.random.choice(data.size, size=num_elements_to_replace, replace=False)
data.ravel()[indices_to_replace] = np.nan

# Find the mean of the matrix while ignoring missing values
mean_without_missing = np.nanmean(data)

# Replace missing values with the mean
data[np.isnan(data)] = mean_without_missing

# Print the data matrix with missing values replaced
print("Data Matrix with Missing Values Replaced:")
print(data)

Data Matrix with Missing Values Replaced:
[[67.   14.   20.   52.   51.75]
 [55.   51.   50.   51.75 99.  ]
 [31.   51.75 51.75 51.75 30.  ]
 [85.   80.   51.75 34.   51.75]
 [22.   51.75 51.75 92.   46.  ]]


### Short Explanations For Some Of The Used Terms

##### Z-score normalization: In simple terms, z-score normalization is a method used to scale or standardize values in a dataset so that they can be compared accurately. For example, imagine you have two different tests scored out of 100 and 10. If you scored 80 on the first test and 8 on the second, it’s hard to compare these directly because they’re on different scales. But if we convert these scores to z-scores, we’ll be able to compare them directly because they’ll be on the same scale. Z-scores tell you how many standard deviations a value is from the average (mean). A z-score of 0 indicates the value is exactly average, a positive z-score indicates it’s above average, and a negative z-score indicates it’s below average.


##### Dot product of two vectors: The dot product is a way of multiplying two vectors together to get a single number (a scalar). This can tell you a lot about the relationship between the two vectors. For example, if the dot product is zero, the vectors are perpendicular to each other. In a 3D space, think of it as the amount one vector ‘goes in the direction’ of another. It’s used in many areas of data science and computer graphics.


##### Identity matrix: An identity matrix is a special kind of square matrix where all the elements of the principal diagonal are ones and all other elements are zeros. It’s called the “identity” matrix because, when it is multiplied by any matrix, the original matrix is returned, similar to how multiplying a number by one leaves the original number unchanged.


##### Eigenvalues and Eigenvectors: These are a way of breaking down matrices, which can make them easier to analyze. An eigenvector is a vector that only changes by a scalar factor when a matrix is multiplied by it. The corresponding eigenvalue is the factor by which the eigenvector is scaled. These concepts are foundational to many areas of linear algebra and are used in many algorithms in data science and machine learning.


##### Mean: The mean is a measure of central tendency, commonly known as the average. To find the mean of a dataset, you add up all of the numbers and then divide by the number of numbers. For example, the mean of 2, 3, and 4 is (2+3+4) / 3 = 3. The mean gives a ‘middle’ or ‘typical’ value for a set of data, but it can be influenced by extreme values (outliers).