Exercise 1 Part 1

Import the numpy package under the name np.

In [1]:
import numpy as np

Exercise 1 Part 2

Create a vector* of zeros with size 10 using np.zeros().
Example output: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [2]:
zeros_vector = np.zeros(10)
print(zeros_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Exercise 1 Part 3

Compute the memory size* of any array. Note: You can do this by multiplying the length of the array by the size of one array element, which you can find using the .itemsize attribute.

Example output: `80` (for an array of size 10 with elements of type float64)

In [3]:
any_array = np.array([1, 2, 3, 4, 5], dtype=np.float64)

memory_size = any_array.size * any_array.itemsize

print(memory_size)

40


Exercise 1 Part 4

In [4]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

Exercise 1 Part 5

In [5]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Exercise 1 Part 6

In [6]:
reversed_array = array[::-1]
reversed_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Exercise 1 Part 7

In [7]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
matrix = np.reshape(array,(3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Exercise 1 Part 8

In [9]:
array = [1,2,0,0,4,0]
non_zero = np.nonzero(array)
non_zero

(array([0, 1, 4]),)

Exercise 1 Part 9

In [10]:
matrix2 = np.eye(3)
matrix2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Exercise 1 Part 10 V1

In [11]:
matrix_5x5 = np.zeros((5, 5))
matrix_5x5 += np.arange(5)
matrix_5x5

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

Exercise 1 Part 10 V2

In [12]:
row_values = np.arange(5)
matrix_5x5 = np.tile(row_values, (5, 1))
matrix_5x5


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Exercise 1 Part 11

In [13]:
vector = np.linspace(0.09090909, 0.90909091, num=10)
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Exercise 1 Part 12

In [14]:
random_vector = np.random.rand(10)
random_sorted_vector = np.sort(random_vector)

print(random_sorted_vector)

[0.14406874 0.29276918 0.30065529 0.489281   0.63117482 0.6725565
 0.68077236 0.75012036 0.84809313 0.9067019 ]


Exercise 1 Part 13

In [15]:
import numpy as np

# Integer types
int8_info = np.iinfo(np.int8)
int32_info = np.iinfo(np.int32)
int64_info = np.iinfo(np.int64)

# Floating-point types
float32_info = np.finfo(np.float32)
float64_info = np.finfo(np.float64)

# Print minimum and maximum representable values
print("Integer Types:")
print(f"int8:  Min = {int8_info.min}, Max = {int8_info.max}")
print(f"int32: Min = {int32_info.min}, Max = {int32_info.max}")
print(f"int64: Min = {int64_info.min}, Max = {int64_info.max}")

print("\nFloating-Point Types:")
print(f"float32: Min = {float32_info.min}, Max = {float32_info.max}")
print(f"float64: Min = {float64_info.min}, Max = {float64_info.max}")


Integer Types:
int8:  Min = -128, Max = 127
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807

Floating-Point Types:
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308


Exercise 1 Part 14

In [16]:
float_array = np.array([1.5, 2.7, 3.2, 4.8], dtype=np.float32)
int_array = float_array.astype(np.int32)
print(int_array)

[1 2 3 4]


Exercise 1 Part 15

In [17]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
row_means = np.mean(matrix, axis=1)
row_means

array([1., 4., 7.])

In [19]:
new_matrix = matrix - row_means[:, np.newaxis]
new_matrix

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

Exercise 1 Part 16

In [34]:
import numpy as np

# Sample 2D array
array = np.array([[5, 9, 3],
                  [1, 4, 6],
                  [7, 0, 9]])

# Column to sort by (n), zero-indexed
n = 0

# Get the indices that would sort the nth column
sorted_indices = np.argsort(array[:, n])

# Use these indices to sort the entire array
sorted_array = array[sorted_indices]

sorted_array


array([[1, 4, 6],
       [5, 9, 3],
       [7, 0, 9]])

Exercise 1 Part 17

In [35]:
sample_array = np.array([[0, 1, 2], 
                         [3, 4, 5], 
                         [6, 7, 8]])

sample_array[[0, 1]] = sample_array[[1, 0]]

sample_array

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Exercise 1 Part 18

In [36]:
# Example bincount array C
C = np.array([1, 2, 3, 4])

# Create an array A such that np.bincount(A) == C
# Using np.repeat, where we repeat each index by its count in C
A = np.repeat(np.arange(len(C)), C)

# Print the array A
A

array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3])

# Short Explanations For Some Of The Used Terms

#### Vector: A vector is a one-dimensional array. It is a sequence of numbers that can represent various mathematical concepts

#### Memory size: The memory size of an array is the total amount of space, usually in bytes, that the array occupies in memory.

#### Matrix: A matrix is a two-dimensional array. It is a grid of numbers arranged in rows and columns.

#### Scalar type: A scalar type in numpy is a type that represents a single number. This includes integer types (like int8, int32, int64), floating point types (like float32, float64), and complex number types.

#### Mean: The mean is the average of a set of numbers. You calculate it by summing up all the numbers and then dividing by the count of the numbers.

#### Bincount: A bincount of an array gives the count of each value in the array. For example, the bincount of [0, 0, 1, 1, 1, 2] is [2, 3, 1], because there are 2 zeros, 3 ones, and 1 two.