In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
sales = [0, 5, 155, 0, 518, 9, 1827,616, 317, 325]
sales_array = np.array(sales)

In [ ]:
sales_array

array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

### ndim - dimensions (axes) in the array
### shape- the size of the array in each dimention
### size - the total numbe
### dtype - the data type

In [ ]:
print(f"ndim: {sales_array.ndim}")

ndim: 1


In [ ]:
print(f"shape: {sales_array.shape}")

shape: (10,)


In [ ]:
print(f"size: {sales_array.size}")

size: 10


In [ ]:
print(f"dtype: {sales_array.dtype}")

dtype: int32


In [ ]:
sales = [[0, 5, 155, 0, 518], [9, 1827,616, 317, 325]]
sales_array = np.array(sales)

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
print(f"ndim: {sales_array.ndim}")


ndim: 2


In [ ]:
print(f"shape: {sales_array.shape}")

shape: (2, 5)


In [ ]:
print(f"size: {sales_array.size}")

size: 10


In [ ]:
print(f"dtype: {sales_array.dtype}")

dtype: int32


In [ ]:
my_list = [x * 10 for x in range (1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [ ]:

my_array = np.array(my_list)

In [ ]:
print(f'shape: {my_array.shape}')

shape: (10,)


In [ ]:
my_array.ndim

1

In [ ]:
my_array.shape

(10,)

In [ ]:
my_array.size

10

In [ ]:
my_array.dtype

dtype('int64')

In [ ]:
my_two_dim_array = my_array.reshape(5,2)
my_two_dim_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [ ]:
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
zeros = np.zeros((5,5), dtype=int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
zeros.dtype

dtype('int64')

In [ ]:
myrange = np.arange(10)
myrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_linspace = np.linspace(0,100,5)
my_linspace

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.arange(1,192,2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191])

In [ ]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
np.arange(1,187,2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185])

### np.default_rng(seed)
### default_rng.random(n)
### default_rng.normal(mean,stdev, n)

In [ ]:
rng = np.random.default_rng(2222) 
# usually it is random but we can specify the default 
random_array = rng.random(10)
random_array

array([0.31795561, 0.27481238, 0.14987102, 0.45281912, 0.97248042,
       0.5906709 , 0.31928325, 0.46330719, 0.90628454, 0.64878647])

In [ ]:
random_normal = rng.normal(5, 1, 10)
random_normal

array([4.36284252, 4.60450772, 3.83043857, 4.63452412, 4.13104347,
       5.74312454, 4.19740365, 2.89130483, 4.41776429, 5.95528344])

In [ ]:
my_a_array =np.arange(10, 101, 10).reshape(5,2)
my_a_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [ ]:
my_array.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [ ]:
my_lin_array = np.linspace(10,100,10).reshape(5,2)
my_lin_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [ ]:
my_fun_array = (np.arange(1,11)*10).reshape(5,2)
my_fun_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [ ]:
my_rng = np.random.default_rng(2022)
random_array = my_rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [ ]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [ ]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [ ]:
random_array[:, 0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [ ]:
random_array[2,1]

0.04305584439252108

### Arithmetic operators can be used to perform array operations


In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [  11, 1829,  618,  319,  327]])

In [ ]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [ ]:
price = sales_array[1, :]

In [ ]:
price

array([   9, 1827,  616,  317,  325])

In [ ]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

#### Before we do that,

* Add a 5 dollar shipping fee to each price. Call this array total.

#### Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from random_array, reshape it to one dimension. Call this discount_pct.
* Subtract discount_pct FROM 1, store this in pct_owed.
* Multiply pct_owed by total to get the final amount owed.


In [ ]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [ ]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [ ]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [ ]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [ ]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [ ]:
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

### FILTERING ARRAYS
* You can filter arrays by indexing them with a logical test



In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
sales_array[sales_array != 0]

array([   5,  155,  518,    9, 1827,  616,  317,  325])

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array[(sales_array==616)]

array([616])

In [ ]:
sales_array[(sales_array==616) | (sales_array<100)]

array([  0,   5,   0,   9, 616])

In [ ]:
sales_array[(sales_array>100) & (sales_array<500)]

array([155, 317, 325])

In [ ]:
mask = (sales_array>100) & (sales_array<500)
sales_array[mask]

array([155, 317, 325])

In [ ]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
sales_array = sales_array[0,:]
sales_array

array([  0,   5, 155,   0, 518])

In [ ]:
product_array[sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

#### MODIFYING ARRAY VALUES
* You can modify array values by assigning new ones

In [ ]:
sales_array

array([  0,   5, 155,   0, 518])

In [ ]:
sales_array[1] = 25

In [ ]:
sales_array

array([  0,  25, 155,   0, 518])

In [ ]:
sales_array[sales_array == 0] = 5
sales_array

array([  5,  25, 155,   5, 518])

#### The where function

np.where(logicl, value if true, value if false)


In [ ]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
inventory_array = np.array([12,102,18,0,0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [ ]:
np.where(inventory_array<= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
np.where(inventory_array<= 0,"Out of Stock",product_array )

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
#### Array aggregation methods 

In [ ]:
sales = [0, 5, 155, 0, 518, 9, 1827,616, 317, 325]
sales_array = np.array(sales).reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array.sum()

3772

In [ ]:
sales_array.mean()

377.2

In [ ]:
sales_array.max()

1827

In [ ]:
sales_array.min()

0

In [ ]:
sales_array.sum(axis=0)

array([   9, 1832,  771,  317,  843])

In [ ]:
sales_array.sum(axis=1)

array([ 678, 3094])

In [ ]:
np.median(sales_array)

236.0

In [ ]:
np.percentile(sales_array,90)

737.0999999999996

In [ ]:
np.unique(sales_array)

array([   0,    5,    9,  155,  317,  325,  518,  616, 1827])

In [ ]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 3.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array.sort()

In [ ]:
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=0)

In [ ]:
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=1)
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
def for_loop_multiply_list(list1,list2):
    product_list = []
    for element1, element2 in zip(list1,list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_arrays(array1, array2):
    return array1 * array2

In [ ]:
list1 = list(range(1000))
list2 = list(range(1000))

In [ ]:
%%timeit -r 5 -n 10000
for_loop_multiply_list(list1,list2)

112 µs ± 10.1 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [ ]:
array1 = np.array(list1)
array2 = np.array(list2)



In [ ]:
%%timeit -r 5 -n 10000
multiply_arrays(array1,array2)

2.48 µs ± 889 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [  11, 1829,  618,  319,  327]])

In [ ]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [ ]:
price = sales_array[1, :]

In [ ]:
price

array([   9, 1827,  616,  317,  325])

In [ ]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

#### Before we do that,

* Add a 5 dollar shipping fee to each price. Call this array total.

#### Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from random_array, reshape it to one dimension. Call this discount_pct.
* Subtract discount_pct FROM 1, store this in pct_owed.
* Multiply pct_owed by total to get the final amount owed.


In [ ]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [ ]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [ ]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [ ]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [ ]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [ ]:
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

### FILTERING ARRAYS
* You can filter arrays by indexing them with a logical test



In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
sales_array[sales_array != 0]

array([   5,  155,  518,    9, 1827,  616,  317,  325])

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array[(sales_array==616)]

array([616])

In [ ]:
sales_array[(sales_array==616) | (sales_array<100)]

array([  0,   5,   0,   9, 616])

In [ ]:
sales_array[(sales_array>100) & (sales_array<500)]

array([155, 317, 325])

In [ ]:
mask = (sales_array>100) & (sales_array<500)
sales_array[mask]

array([155, 317, 325])

In [ ]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
sales_array = sales_array[0,:]
sales_array

array([  0,   5, 155,   0, 518])

In [ ]:
product_array[sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

#### MODIFYING ARRAY VALUES
* You can modify array values by assigning new ones

In [ ]:
sales_array

array([  0,   5, 155,   0, 518])

In [ ]:
sales_array[1] = 25

In [ ]:
sales_array

array([  0,  25, 155,   0, 518])

In [ ]:
sales_array[sales_array == 0] = 5
sales_array

array([  5,  25, 155,   5, 518])

#### The where function

np.where(logicl, value if true, value if false)


In [ ]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
inventory_array = np.array([12,102,18,0,0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [ ]:
np.where(inventory_array<= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
np.where(inventory_array<= 0,"Out of Stock",product_array )

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
#### Array aggregation methods 

In [ ]:
sales = [0, 5, 155, 0, 518, 9, 1827,616, 317, 325]
sales_array = np.array(sales).reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array.sum()

3772

In [ ]:
sales_array.mean()

377.2

In [ ]:
sales_array.max()

1827

In [ ]:
sales_array.min()

0

In [ ]:
sales_array.sum(axis=0)

array([   9, 1832,  771,  317,  843])

In [ ]:
sales_array.sum(axis=1)

array([ 678, 3094])

In [ ]:
np.median(sales_array)

236.0

In [ ]:
np.percentile(sales_array,90)

737.0999999999996

In [ ]:
np.unique(sales_array)

array([   0,    5,    9,  155,  317,  325,  518,  616, 1827])

In [ ]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 3.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array.sort()

In [ ]:
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=0)

In [ ]:
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=1)
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
def for_loop_multiply_list(list1,list2):
    product_list = []
    for element1, element2 in zip(list1,list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_arrays(array1, array2):
    return array1 * array2

In [ ]:
list1 = list(range(1000))
list2 = list(range(1000))

In [ ]:
%%timeit -r 5 -n 10000
for_loop_multiply_list(list1,list2)

112 µs ± 10.1 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [ ]:
array1 = np.array(list1)
array2 = np.array(list2)



In [ ]:
%%timeit -r 5 -n 10000
multiply_arrays(array1,array2)

2.48 µs ± 889 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [  11, 1829,  618,  319,  327]])

In [ ]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [ ]:
price = sales_array[1, :]

In [ ]:
price

array([   9, 1827,  616,  317,  325])

In [ ]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

#### Before we do that,

* Add a 5 dollar shipping fee to each price. Call this array total.

#### Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from random_array, reshape it to one dimension. Call this discount_pct.
* Subtract discount_pct FROM 1, store this in pct_owed.
* Multiply pct_owed by total to get the final amount owed.


In [ ]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [ ]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [ ]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [ ]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [ ]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [ ]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [ ]:
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

### FILTERING ARRAYS
* You can filter arrays by indexing them with a logical test



In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
sales_array[sales_array != 0]

array([   5,  155,  518,    9, 1827,  616,  317,  325])

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array[(sales_array==616)]

array([616])

In [ ]:
sales_array[(sales_array==616) | (sales_array<100)]

array([  0,   5,   0,   9, 616])

In [ ]:
sales_array[(sales_array>100) & (sales_array<500)]

array([155, 317, 325])

In [ ]:
mask = (sales_array>100) & (sales_array<500)
sales_array[mask]

array([155, 317, 325])

In [ ]:
product_array = np.array(['fruits','vegetables','cereal','dairy','eggs'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
sales_array = sales_array[0,:]
sales_array

array([  0,   5, 155,   0, 518])

In [ ]:
product_array[sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

#### MODIFYING ARRAY VALUES
* You can modify array values by assigning new ones

In [ ]:
sales_array

array([  0,   5, 155,   0, 518])

In [ ]:
sales_array[1] = 25

In [ ]:
sales_array

array([  0,  25, 155,   0, 518])

In [ ]:
sales_array[sales_array == 0] = 5
sales_array

array([  5,  25, 155,   5, 518])

#### The where function

np.where(logicl, value if true, value if false)


In [ ]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [ ]:
inventory_array = np.array([12,102,18,0,0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [ ]:
np.where(inventory_array<= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
np.where(inventory_array<= 0,"Out of Stock",product_array )

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [ ]:
#### Array aggregation methods 

In [ ]:
sales = [0, 5, 155, 0, 518, 9, 1827,616, 317, 325]
sales_array = np.array(sales).reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array.sum()

3772

In [ ]:
sales_array.mean()

377.2

In [ ]:
sales_array.max()

1827

In [ ]:
sales_array.min()

0

In [ ]:
sales_array.sum(axis=0)

array([   9, 1832,  771,  317,  843])

In [ ]:
sales_array.sum(axis=1)

array([ 678, 3094])

In [ ]:
np.median(sales_array)

236.0

In [ ]:
np.percentile(sales_array,90)

737.0999999999996

In [ ]:
np.unique(sales_array)

array([   0,    5,    9,  155,  317,  325,  518,  616, 1827])

In [ ]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 3.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [ ]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [ ]:
sales_array.sort()

In [ ]:
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=0)

In [ ]:
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
sales_array.sort(axis=1)
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [ ]:
def for_loop_multiply_list(list1,list2):
    product_list = []
    for element1, element2 in zip(list1,list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_arrays(array1, array2):
    return array1 * array2

In [ ]:
list1 = list(range(1000))
list2 = list(range(1000))

In [ ]:
%%timeit -r 5 -n 10000
for_loop_multiply_list(list1,list2)

112 µs ± 10.1 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [ ]:
array1 = np.array(list1)
array2 = np.array(list2)



In [ ]:
%%timeit -r 5 -n 10000
multiply_arrays(array1,array2)

2.48 µs ± 889 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)
